#!/usr/bin/env python3
"""m68k_cyc_mame.py musashi.h > src/m2_m68k_cyc.h: correct the 68000 base cycle table that
tools/m68k_cyc.c takes from Musashi to MAME's m68000 (the microcoded core its genesis
driver runs), as measured opcode by opcode by tools/optiming.

The input is m68k_cyc.c's output (git show <rev>:src/m2_m68k_cyc.h from before the
correction will do). The data-dependent parts stay in src/m2_m68k.h and tools/m68krecomp.py:
MUL, DIV, the bit number of BCHG/BCLR/BSET on a register, Scc true.
"""
import re, sys


def load(text):
    idx = [int(x) for x in re.findall(r'\d+', text[text.index('{') + 1:text.index('}')])]
    blks = [[int(x) for x in b.split(',')] for b in re.findall(r'\{([\d,]+)\}', text[text.index('m68k_cyc_blk'):])]
    assert len(idx) == 1024
    return [blks[idx[op >> 6]][op & 63] for op in range(65536)]


def fix(c):
    def adj(ops, frm, to):
        for op in ops:
            assert c[op] == frm, '%04x: %d, not %d' % (op, c[op], frm)
            c[op] = to
    R = range(8)
    for base in (0xd080, 0x9080, 0xc080, 0x8080):              # ADD/SUB/AND/OR.L Dn,Dn
        adj([base | rx << 9 | r for rx in R for r in R], 6, 8)
    for base in (0xd080, 0x9080, 0xd1c0, 0x91c0):              # ADD/SUB.L An,Dn; ADDA/SUBA.L Dn/An
        adj([base | rx << 9 | 8 | r for rx in R for r in R], 6, 8)
    adj([b | rx << 9 | r for b in (0xd1c0, 0x91c0) for rx in R for r in R], 6, 8)
    adj([b | rx << 9 | 0x3c for b in (0xd0c0, 0x90c0) for rx in R], 14, 12)   # ADDA/SUBA.W #
    adj([b | s | rx << 9 | 0x3c for b in (0xd000, 0x9000, 0xc000, 0x8000)    # ADD/SUB/AND/OR
         for s in (0, 0x40) for rx in R], 10, 8)                             #  .B/.W #,Dn
    adj([0x5048 | q << 9 | r for q in R for r in R], 4, 8)                   # ADDQ.W #,An
    adj([0x0280 | r for r in R], 14, 16)                                     # ANDI.L #,Dn
    adj([0x013c | rx << 9 for rx in R], 8, 10)                               # BTST Dn,#
    adj([0x50c0 | r for r in R], 6, 4)                                       # ST Dn (+2: true)
    for op in range(0x4ad0, 0x4afa):                                         # TAS <mem>
        if (op & 0x38) != 0x08: c[op] -= 4
    for b, frm in ((0x0140, 8), (0x0180, 10), (0x01c0, 8)):                  # BCHG/BCLR/BSET
        adj([b | rx << 9 | r for rx in R for r in R], frm, frm - 2)          #  Dn,Dn: bit < 16
    for b, frm in ((0x0840, 12), (0x0880, 14), (0x08c0, 12)):                #  #,Dn
        adj([b | r for r in R], frm, frm - 2)
    for op in range(65536):                                                  # DIVU/DIVS: the EA
        if op & 0xf0c0 == 0x80c0 and (op & 0x38) != 0x08 and op & 0x3f <= 0x3c:
            c[op] -= 158 if op & 0x100 else 140
            assert c[op] >= 0
    return c


def write(c, out):
    nb, blk, seen = 0, [], {}
    for i in range(1024):
        k = tuple(c[i * 64:i * 64 + 64])
        if k not in seen: seen[k] = len(seen)
        blk.append(seen[k])
    out.write("/* m2_m68k_cyc.h - generated by tools/m68k_cyc.c from Musashi (MIT licence,\n"
              " * (c) 1998-2001 Karl Stenerud) and corrected to MAME's m68000 by\n"
              " * tools/m68k_cyc_mame.py: 68000 base cycles per opcode. Do not edit.\n"
              " * M68K_CYC(op) = m68k_cyc_blk[m68k_cyc_idx[op >> 6]][op & 63]. */\n"
              "#ifndef M2_M68K_CYC_H\n#define M2_M68K_CYC_H\n"
              "static const unsigned char m68k_cyc_idx[1024] = {\n")
    out.write(''.join('%d%s' % (b, '\n' if i == 1023 else ',\n' if (i & 31) == 31 else ',') for i, b in enumerate(blk)))
    out.write("};\nstatic const unsigned char m68k_cyc_blk[%d][64] = {\n" % len(seen))
    out.write(',\n'.join('{' + ','.join(map(str, k)) + '}' for k in seen) + '\n')
    out.write("};\n#define M68K_CYC(op) (m68k_cyc_blk[m68k_cyc_idx[(op) >> 6]][(op) & 63])\n#endif\n")


if __name__ == '__main__':
    text = open(sys.argv[1]).read()
    if 'm68k_cyc_mame' in text: sys.exit('%s is already corrected: give m68k_cyc.c\'s output' % sys.argv[1])
    write(fix(load(text)), sys.stdout)
