/*
 * m68k_cyc.c — write src/m2_m68k_cyc.h: the 68000's base cycles for each of the 65536
 * opcodes, as Musashi's opcode table has them (m68ki_cycles[M68K_CPU_TYPE_68000]), in
 * 5.5 KB instead of 64 (the i960's program ROM is shared with the game).
 * src/m2_m68k.h charges these per instruction and adds the variable parts itself.
 *
 *   git clone https://github.com/kstenerud/Musashi && make -C Musashi
 *   cc -IMusashi -o m68k_cyc tools/m68k_cyc.c Musashi/m68kcpu.o Musashi/m68kops.o \
 *      Musashi/m68kdasm.o Musashi/softfloat/softfloat.o -lm
 *   ./m68k_cyc > src/m2_m68k_cyc.h
 */
#include <stdio.h>
#include <string.h>
#include "m68k.h"

extern unsigned char m68ki_cycles[][0x10000];
unsigned int m68k_read_memory_8(unsigned int a) { (void)a; return 0; }
unsigned int m68k_read_memory_16(unsigned int a) { (void)a; return 0; }
unsigned int m68k_read_memory_32(unsigned int a) { (void)a; return 0; }
void m68k_write_memory_8(unsigned int a, unsigned int v) { (void)a; (void)v; }
void m68k_write_memory_16(unsigned int a, unsigned int v) { (void)a; (void)v; }
void m68k_write_memory_32(unsigned int a, unsigned int v) { (void)a; (void)v; }
unsigned int m68k_read_disassembler_16(unsigned int a) { (void)a; return 0; }
unsigned int m68k_read_disassembler_32(unsigned int a) { (void)a; return 0; }

int main(void) {
    static int blk[1024];
    int i, j, nb = 0;
    const unsigned char *c;
    m68k_init();
    m68k_set_cpu_type(M68K_CPU_TYPE_68000);
    c = m68ki_cycles[0];
    /* the table is 1024 blocks of 64 (the low six bits: the EA mode and register), and
     * only ~70 blocks differ: an index per block and the distinct blocks */
    for (i = 0; i < 1024; i++) {
        for (j = 0; j < i; j++)
            if (!memcmp(c + i * 64, c + j * 64, 64)) break;
        blk[i] = j < i ? blk[j] : nb++;
    }
    printf("/* m2_m68k_cyc.h - generated by tools/m68k_cyc.c from Musashi (MIT licence,\n"
           " * (c) 1998-2001 Karl Stenerud): 68000 base cycles per opcode. Do not edit.\n"
           " * M68K_CYC(op) = m68k_cyc_blk[m68k_cyc_idx[op >> 6]][op & 63]. */\n"
           "#ifndef M2_M68K_CYC_H\n#define M2_M68K_CYC_H\n"
           "static const unsigned char m68k_cyc_idx[1024] = {\n");
    for (i = 0; i < 1024; i++) printf("%d%s", blk[i], i == 1023 ? "\n" : (i & 31) == 31 ? ",\n" : ",");
    printf("};\nstatic const unsigned char m68k_cyc_blk[%d][64] = {\n", nb);
    for (j = 0; j < nb; j++) {
        for (i = 0; i < 1024 && blk[i] != j; i++) { }
        printf("{");
        for (int k = 0; k < 64; k++) printf("%d%s", c[i * 64 + k], k == 63 ? "" : ",");
        printf("}%s\n", j == nb - 1 ? "" : ",");
    }
    printf("};\n#define M68K_CYC(op) (m68k_cyc_blk[m68k_cyc_idx[(op) >> 6]][(op) & 63])\n#endif\n");
    return 0;
}
