#!/usr/bin/env python3
"""mdrom.py <cartridge.bin | .md | .gen | .zip> [-o header]

Packs a Mega Drive cartridge image for src/sonic.c: src/sonic_rom.h, the ROM as 16-bit
words (the even byte in the high half), the form md_hw.h reads it in. Takes a plain
(big-endian, not interleaved) image, or a zip holding one. The header is Sega's ROM
data: gitignored, never commit it.

Checked against Sonic the Hedgehog (W) (REV00), 512 KB, sha1 4c3b606bec697b0b934ba2f650a8b83c0e3b77c7
(MAME's software list `sonic`, "sonic the hedgehog (usa, europe).md").
"""
import argparse, hashlib, os, sys, zipfile

KNOWN = {'4c3b606bec697b0b934ba2f650a8b83c0e3b77c7': 'Sonic the Hedgehog (W) (REV00)'}


def load(path):
    if zipfile.is_zipfile(path):
        with zipfile.ZipFile(path) as z:
            names = [n for n in z.namelist() if not n.endswith('/')]
            names.sort(key=lambda n: -z.getinfo(n).file_size)
            return z.read(names[0]), '%s:%s' % (os.path.basename(path), names[0])
    with open(path, 'rb') as f:
        return f.read(), os.path.basename(path)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('rom')
    ap.add_argument('-o', '--out', default=os.path.join(os.path.dirname(__file__), '..', 'src', 'sonic_rom.h'))
    a = ap.parse_args()
    data, src = load(a.rom)
    if data[0x100:0x104] != b'SEGA' and data[0x101:0x105] != b'SEGA':
        sys.exit('%s: no "SEGA" at 0x100: not a plain Mega Drive image (interleaved .smd?)' % src)
    if len(data) & 1:
        data += b'\xff'
    sha = hashlib.sha1(data).hexdigest()
    title = KNOWN.get(sha, 'unknown dump (sha1 %s)' % sha)
    words = [(data[i] << 8) | data[i + 1] for i in range(0, len(data), 2)]
    with open(a.out, 'w') as f:
        f.write('/* Generated by tools/mdrom.py from %s: %s. Sega ROM data, never commit. */\n' % (src, title))
        f.write('#ifndef SONIC_ROM_H\n#define SONIC_ROM_H\n')
        f.write('#define MD_ROM_WORDS %du\n' % len(words))
        f.write('static const u16 md_rom[%d] = {\n' % len(words))
        for i in range(0, len(words), 16):
            f.write(','.join('0x%04x' % w for w in words[i:i + 16]) + ',\n')
        f.write('};\n#endif\n')
    print('%s: %s, %d KB -> %s' % (src, title, len(data) // 1024, os.path.normpath(a.out)))


if __name__ == '__main__':
    main()
